package com.sfs.lifecycle.model;

public enum LifecycleEventType {

    REGISTRATION_RECORDED,
    ANALYSIS_STARTED,
    ANALYSIS_SUCCEEDED,
    ANALYSIS_FAILED,
    ANALYSIS_REFUSED,
    MEMORY_COMMIT_REQUESTED,
    DNA_VALIDATED,
    MEMORY_COMMITTED,
    MEMORY_COMMIT_REFUSED,
    SOFT_DELETED,
    SOFT_DELETE_REFUSED,
    UNDO_DELETED,
    UNDO_DELETE_REFUSED,
    PURGE_REQUESTED,
    RAW_RELEASED,
    PURGE_REFUSED,
    METADATA_UPDATED,
    METADATA_UPDATE_REFUSED,
    VERSION_ADDED,
    VERSION_ADD_REFUSED,
    MEMORIZE_INTERRUPTED
}

